### ISSUE TITLE
Fix formatting of nested message types

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/openapi2proto#21]
Ever since the update that added comments, nested messages are missing an indent

**Comment by lestrrat** [comment]
@jprobinson Can you provide test cases for this? A single new test case is fine, I can change the other fixtures accordingly.

Also, if/when I make a PR, can I *please* ditch using `text/template`. TBH using `io.Writer` / `bytes.Buffer` is much easier...

**Comment by lestrrat** [comment]
@jprobinson I've got this down up to the point where I'm now fixing the fixtures. I'll send a PR once it's done. (Note: current implementation relies on #73 -- I can change this if yo don't like #73, but just FYI)
