### ISSUE TITLE
Externally defined objects

### ISSUE THREAD

**Issue by sysradium** [NYTimes/openapi2proto#27]
I tried to use externally defined types with openapi2proto but could not make it work nicely.

I found a PR which makes the parsers aware of the external paths in `$ref` however it produces weird results.

For example, if you define a type with:
```
          schema:
            $ref: 'Pet.yaml'
```
It creates a service with `Pet.yaml`:
```
rpc PostPets(PostPetsRequest) returns (Pet.yaml) {}
```
At the same time in the object you use that ref in it replaces the filepath with the package name + message name as I expect:
```
message GetPetsResponse {
    repeated pet.Pet items = 1;
}
```

Besides that I see no `import pets.proto` added and lastly - who is responsible for generating the `pets.proto` file? It seems impossible by design for openapi2proto to produce it as it spits the generated proto to the stdout, which presumes you to have just one final file.

I tried using openapi2proto with the particular `Pey.yaml` file. It produced just an empty proto file. 
So can you explain how can we split swagger API spec and models definitions and still be able to use this tool?

PS. The Pey example I've used is located here https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/yaml/petstore-separate/spec

**Comment by jprobinson** [comment]
Howdy @sysradium!

I also noticed a lil funkiness in external references recently when I tried using them. The current setup expects a file refs to be pointing at `.proto` files and to be formatted like as a [JSON reference object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#referenceObject):

```{import path}#/{definitions|parameters}/{typeName}```

For example:

```$ref: 'google/protobuf/timestamp.proto#/google.protobuf.Timestamp'```

Should add a `import google/protobuf/timestamp.proto` at the top and have `google.protobuf.Timestamp` listed as the type, but the current implementation is title casing the type to be `Google.Protobuf.Timestamp`.

Using this format _may_ work for you. Have you tried something like

`$ref: 'pet.proto#/Pet'`?

**Comment by sysradium** [comment]
Thanks for that tremendously fast feedback.
```{import path}#/{definitions|parameters}/{typeName}```
I used that as:
```
        "200":
          description: pet response
          schema:
            $ref: 'Pet.yaml#/definitions/Pet'
```
Considered the `Pet.yaml` an import path. Sadly enough this produced:
```
rpc GetPetsId(GetPetsIdRequest) returns (Pet.yaml#/definitions/Pet) {}
```
With `pet.proto` I get:
```
    rpc GetPetsId(GetPetsIdRequest) returns (pet.proto#/Pet) {}
```
And no import_path.  According to the code it should be either yaml or json.
https://github.com/NYTimes/openapi2proto/blob/master/openapi.go#L144
Which is expected and follows OpenAPI standards. 

Also even if that would work how am I supposed to generate that `pet.proto` ...

PS.

BTW if ref is being used under `parameters` section:
```
      parameters:
        - $ref: 'parameters.yaml#/tagsParam'
```
I get:
```
2017/08/14 22:54:06 unable to find referenced type for parameter: &openapi2proto.Items{Description:"", Type:interface {}(nil), Format:interface {}(nil), Enum:[]string(nil), ProtoTag:0, AdditionalProperties:(*openapi2proto.Items)(nil), Ref:"parameters.yaml#/tagsParam", Items:(*openapi2proto.Items)(nil), In:"", Schema:(*openapi2proto.Items)(nil), Model:openapi2proto.Model{Properties:map[string]*openapi2proto.Items(nil), Name:"", Depth:0}}
```
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-separate/spec/parameters.yaml
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-separate/spec/swagger.yaml#L31

**Comment by jprobinson** [comment]
Referencing external docs is where things start getting a tad weird with this tool as the Open API spec wants to link to other Open API specs and Protobufs want to link to actual protobuf specs.

2 options right now:

1. Reference the Open API definition in your yaml spec so documentation tooling can play nice. Then add in something to replace `s/yaml/proto` in the imports before running `protoc`.
2. Reference the .proto file in your yaml spec. Swagger/OpenAPI viewers wont be able to read the reference but you'll be able to hand the `openapi2proto` result directly to `protoc`

Also, I've just pushed a commit that will _not_ title case references if it has a package name on it. I've tested it with `$ref: 'pet.proto#/pet.Pet'` and verified a `import "pet.proto";` at the top along with a `pet.Pet fieldName = 1;` in the spec declaration.

**Comment by sysradium** [comment]
Awesome, will try it out. However how should I generate the `pet.proto` then? openapi2proto produces a proto with an empty service and a missing package name.

**Comment by jprobinson** [comment]
Yep, you'd then need to generate the proto manually.

Do you have an example spec I can write a test with?

**Comment by sysradium** [comment]
As I mentioned - I am using example from https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/yaml/petstore-separate/spec

Because I hope it defines how the things should be.

**Comment by jprobinson** [comment]
OK. This issue gave me the kick in the butt I needed to fix relative paths. Thank you!

Now, any externally referenced Open API specs will get _fetched_ and _inlined_ into the outgoing protobuf spec. For an example of how that works, I've added a protobuf-friendly version of the "petstore" spec under `/fixtures/petstore/`. Take a look and let me know if this fits your needs.

Referencing external protobuf files still works, they just get added as an `import` so you can add the common types like a Timestamp with something like:
```
$ref: "google/protobuf/timestamp.proto#/google.protobuf.Timestamp"
```
I'm currently setting up logic and tests so that remotely referenced (http) Open API specs also get inlined. 

Please let me know if this does not suit your needs!
