### ISSUE TITLE
Add support for parameters with `collectionFormat: csv`

### ISSUE THREAD

**Issue by reusst** [NYTimes/openapi2proto#29]
Hi,

this works:
```
      parameters:
        - name: id
          in: path
          description: ID of pet to use
          required: true
          type: array
          items:
            type: string
          collectionFormat: csv
```
-> `repeated string id = 3;`

Does not work:
```
      parameters:
        - $ref: "#/parameters/id"
...
parameters:
  id:
    in: path
    name: id
    description: ID of pet to use
    required: true
    type: array
    items:
      type: string
    collectionFormat: csv
```
-> 
 ```
array id = 1;
...
repeated int32 id = 1
```
Do you have any idea?

Rgds
Tobi

**Comment by jprobinson** [comment]
Howdy @reusst, sorry for the delayed response.

I believe the issue you're running into is the lack of support for the `collectionFormat` field at the moment.

I think it'd be a handy feature to have so I'm going to update this issue to reflect it.

I hope I can have time to add this soon, but PRs welcome!
