### ISSUE TITLE
Support for proto to swagger ?

### ISSUE THREAD

**Issue by boyand** [NYTimes/openapi2proto#4]
The tool looks great! Thanks for sharing this. Are there any plans to somehow support the reverse ( i.e. proto3 to swagger or json schema ? )

**Comment by jprobinson** [comment]
Howdy @boyand, thanks for the feedback! 

The [grpc-gateway](https://github.com/gengo/grpc-gateway) project takes a Protobuf-first approach and actually has a tool to do what you're looking for: [protoc-gen-swagger](https://github.com/gengo/grpc-gateway/tree/master/protoc-gen-swagger). 

For now, this project is going to stick with the Swagger-first approach, but the tool above should hopefully help you out.

**Comment by chrusty** [comment]
@boyand you could try this: https://github.com/chrusty/protoc-gen-jsonschema
