### ISSUE TITLE
Snake to Camel Case

### ISSUE THREAD

**Issue by genexp** [NYTimes/openapi2proto#41]
Currently, the library doesn't do much work on the path name received from swagger.  As an example, it converts POST: /queue/{id}/enqueue_player to something like PostQueuesIdEnqueue_player.  I think I'd like that to be PostQueuesIdEnqueueGroup, which seems like a good default for the library.  Mind if I send a pull request for this?

**Comment by jprobinson** [comment]
Yep! Sounds like a good idea, thanks!
