### ISSUE TITLE
Integer Parameter Definition Object

### ISSUE THREAD

**Issue by garyluu** [NYTimes/openapi2proto#45]
Appears to be an issue converting [Parameters Definitions Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parametersDefinitionsObject) with type integer even when format is specified.  Can be reproduced by changing SpecificConceptParam in https://github.com/NYTimes/openapi2proto/blob/master/fixtures/semantic_api.json to 
```
   "SpecificConceptParam": {
        "name": "specific-concept",
        "in": "path",
        "description": "The name of the concept, used for Constructing a Semantic API Request by Concept Type and Specific Concept Name. The parameter is defined in the URI path, as the element immediately preceding \".json\" like with \"Baseball.json\".\n",
        "required": true,
        "type": "integer",
        "format": "int32"
}
```

Currently, the resulting .proto shows "integer" instead of the expected "int32"

```
   string query = 3;
   integer specific_concept = 4;
}
```

**Comment by jprobinson** [comment]
Oof. Definitely looks like a bug with parameters from looking at the code around here. I'll try and find some time to look into it this week.

Thanks for reporting, @garyluu!
