### ISSUE TITLE
fails on example swagger document

### ISSUE THREAD

**Issue by tmc** [NYTimes/openapi2proto#5]
https://apis-guru.github.io/api-models/github.com/v3/swagger.yaml

**Comment by jprobinson** [comment]
Please make sure your swagger file follows the Open API specifications: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject

I see several instances where `items` objects in this file that interpolate between being a nested object and being a nested array. This is preventing the tool from being able to unmarshal the yaml into the `Items` struct and causing the tool to error.
