### ISSUE TITLE
Allow relative and remote schema references in $ref

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/openapi2proto#7]
https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md#guidelines-for-referencing

**Comment by fyelles** [comment]
Any plans to support this thing soon ?

**Comment by jprobinson** [comment]
Howdy Frank,

Sorry for the delay, I'll get this feature in today.

thanks for the bump,
-JP
