### ISSUE TITLE
What should happen when there are multiple `in: body` parameters?

### ISSUE THREAD

**Issue by lestrrat** [NYTimes/openapi2proto#86]
What should this generate for the http annotation? (abbreviated)

```json
parameters:
   - name: foo
      in: body
   - name: bar
      in: body
   - name: baz
      in: body
```

Currently this just takes the first parameter and does

```protobuf
rpc .... {
    option (google.api.http) = {
      body: "foo"
    };
}
```

But this probably isn't right. Reading [this](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) I'm inclined to just assume everything is in the body (i.e. `body: *`)?

**Comment by jprobinson** [comment]
Interesting. I always use just 1 parameter for the "body" and it is always an object.

I imagine if we had multiple parameters pointing to the body, we could create a new 'request' object that contains them? Similar to how we combine parameters with the body now?

**Comment by lestrrat** [comment]
@jprobinson It's been a while, but since then I read up on OpenAPI spec, and came to realize that OpenAPI v2 restricts in: body as a single parameter. My confusion came from the fact that openapi2proto never really complained about this (which is understandable). Anyways, so this issue is moot.

As an aside, since I'm in need to generate a bunch of different things from OpenAPI v2 spec, I'm now just biting the bullet and writing a complete library that parses, validates, and allows safe inspection and modification of OpenAPI. https://github.com/lestrrat-go/openapi
