### ISSUE TITLE
don't know how to handle schema type '[boolean]'

### ISSUE THREAD

**Issue by nickman** [NYTimes/openapi2proto#90]
Attempted to generate proto from the [PagerDuty](https://api-reference.pagerduty.com/output.yaml) swagger spec. Got this error:

`error: failed to transpile: failed to compile OpenAPI spec to Protocol buffers: failed to compile parameters: failed to compile #/parameters/schedule_overflow: don't know how to handle schema type '[boolean]'
`

Simple proposed fix forthcoming.

**Comment by jprobinson** [comment]
resolved in #91
